apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-pod
  name: my-pod
  namespace: ns1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: my-pod
status:
  loadBalancer: {}
