apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-pod
  name: my-pod
  namespace: ns1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-pod
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi
status: {}
