apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ratings-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ratings-api
status:
  loadBalancer: {}
